# docker-compose file to build CLIFF-CLAVIN server
# Steps:
# 1. Build the docker image: docker-compose -f docker-compose-cliff.yml build
# 2. Start up the Docker container (takes a while to build): docker-compose -f docker-compose-cliff.yml up -d
# 3. Monitor the progress of the build: docker-compose -f docker-compose-cliff.yml logs -t -f --tail='all'
# 4. Continue to run in the background: Press Ctrl-C, the CLIFF-CLAVIN server will be running in the background.
#
# Maintainer: Herman Tolentino
# Last Update: 06 Jan 2020
version: "3"

services:
  cliff:
    hostname: cliff
    image: rahulbot/cliff-clavin
    #build:
    #  dockerfile: server_apps/cliff/Dockerfile.1
    #  args:
    #    CLIFF_VERSION: 2.6.1
      #context: server_apps/cliff/.
    environment:
      CLIFF_VERSION: 2.6.1
    container_name: cliff
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl -f http://localhost:8080/ || false"
      timeout: 3s
      retries: 3

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
