#FROM jupyter/scipy-notebook:bb222f49222e
FROM jupyter/r-notebook

USER root

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /home/jovyan/work

RUN ln -sf /bin/bash /bin/sh && \
    ln -s /bin/tar /bin/gtar

# install jupyterlab, jupyter_client
RUN conda install -c conda-forge jupyterlab ipywidgets && \
    conda install jupyter_client && \
    jupyter serverextension enable --py jupyterlab --sys-prefix

RUN conda update notebook jupyterhub jupyterlab

COPY work .

RUN echo "jovyan ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN pwd
RUN chmod a+x modules/*.sh && \
    mkdir -p /srv/modules && \
    mv modules/*.sh /srv/modules

# libav-tools for matplotlib anim
RUN apt-get update && \
    apt-get install -y --no-install-recommends libav-tools nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python 3 packages
# Remove pyqt and qt pulled in for matplotlib since we're only ever going to
# use notebook-friendly backends in these images
RUN chmod -R a+w /opt/conda/

RUN conda install --quiet --yes \
    'nomkl' \
    'ipywidgets=6.0*' \
    'pandas=0.19*' \
    'numexpr=2.6*' \
    'matplotlib=2.0*' \
    'scipy=0.19*' \
    'seaborn=0.7*' \
    'scikit-learn=0.18*' \
    'scikit-image=0.12*' \
    'sympy=1.0*' \
    'cython=0.25*' \
    'patsy=0.4*' \
    'statsmodels=0.8*' \
    'cloudpickle=0.2*' \
    'dill=0.2*' \
    'numba=0.31*' \
    'bokeh=0.12*' \
    'sqlalchemy=1.1*' \
    'hdf5=1.8.17' \
    'h5py=2.6*' \
    'vincent=0.4.*' \
    'beautifulsoup4=4.5.*' \
    'xlrd'  && \
    conda remove --quiet --yes --force qt pyqt && \
    conda clean -tipsy

# Activate ipywidgets extension in the environment that runs the notebook server
RUN jupyter nbextension enable --py widgetsnbextension --sys-prefix

# Install Python 2 packages
# Remove pyqt and qt pulled in for matplotlib since we're only ever going to
# use notebook-friendly backends in these images
RUN conda create --quiet --yes -p $CONDA_DIR/envs/python2 python=2.7 \
    'nomkl' \
    'ipython=5.3*' \
    'ipywidgets=6.0*' \
    'pandas=0.19*' \
    'numexpr=2.6*' \
    'matplotlib=2.0*' \
    'scipy=0.19*' \
    'seaborn=0.7*' \
    'scikit-learn=0.18*' \
    'scikit-image=0.12*' \
    'sympy=1.0*' \
    'cython=0.25*' \
    'patsy=0.4*' \
    'statsmodels=0.8*' \
    'cloudpickle=0.2*' \
    'dill=0.2*' \
    'numba=0.31*' \
    'bokeh=0.12*' \
    'hdf5=1.8.17' \
    'h5py=2.6*' \
    'sqlalchemy=1.1*' \
    'pyzmq' \
    'vincent=0.4.*' \
    'beautifulsoup4=4.5.*' \
    'xlrd' && \
    conda remove -n python2 --quiet --yes --force qt pyqt && \
    conda clean -tipsy

USER $NB_USER

# Add shortcuts to distinguish pip for python2 and python3 envs
RUN ln -s $CONDA_DIR/envs/python2/bin/pip $CONDA_DIR/bin/pip2 && \
    ln -s $CONDA_DIR/bin/pip $CONDA_DIR/bin/pip3

# Import matplotlib the first time to build the font cache.
ENV XDG_CACHE_HOME /home/$NB_USER/.cache/
RUN MPLBACKEND=Agg $CONDA_DIR/envs/python2/bin/python -c "import matplotlib.pyplot"

USER root

# Install Python 2 kernel spec globally to avoid permission problems when NB_UID
# switching at runtime and to allow the notebook server running out of the root
# environment to find it. Also, activate the python2 environment upon kernel
# launch.
RUN pip install kernda --no-cache && \
    $CONDA_DIR/envs/python2/bin/python -m ipykernel install && \
    kernda -o -y /usr/local/share/jupyter/kernels/python2/kernel.json && \
    pip uninstall kernda -y

RUN conda install conda-build && \
    conda clean -tipsy

RUN chmod a+w -R /home/jovyan/work/shared && \
    chmod a+w -R /home/jovyan/work/geoserver && \
    chmod a+w -R /home/jovyan/work/notebooks && \
    chmod a+w /home/jovyan/work/notebooks/*.ipynb

RUN chown -R jovyan:users /home/jovyan && \
    chown -R jovyan:users /home/jovyan/work/shared && \
    chown -R jovyan:users /home/jovyan/work/geoserver && \
    chown -R jovyan:users /home/jovyan/work/notebooks

RUN mkdir -p /home/jovyan/.cache && \
    chmod -R a+w /home/jovyan/.cache && \
    chown -R jovyan:users /home/jovyan/.cache

# Jupyter Themes
RUN git clone https://github.com/dunovank/jupyter-themes.git && \
    cd jupyter-themes && \
    python setup.py install && \
    mkdir -p /opt/conda/lib/python3.6/site-packages/jupyterthemes && \
    mkdir -p /opt/conda/lib/python3.6/site-packages/jupyterthemes-0.16.4-py3.6.egg/jupyterthemes && \
    chmod -R a+w /opt/conda/lib/python3.6/site-packages/jupyterthemes && \
    chmod -R a+w /opt/conda/lib/python3.6/site-packages/jupyterthemes-0.16.4-py3.6.egg/jupyterthemes && \
    cd .. && \
    rm -fvR jupyter-themes

USER jovyan

WORKDIR /home/jovyan/work

# Custom logo
RUN mkdir -p /home/jovyan/.jupyter/custom
ADD custom.css /home/jovyan/.jupyter/custom/custom.css
ADD geeks.png /home/jovyan/.jupyter/custom/geeks.png

RUN /srv/modules/load-python-modules.sh
