FROM postgres:9.5

ARG JPY_PSQL_PASSWORD=0b99e41bffd5138bbdbc1b2fe1ca9a5e3703bd77029f29ead227dc99d41a0d06
ENV JPY_PSQL_PASSWORD ${JPY_PSQL_PASSWORD}
# initdb.sh will be run by the parent container's entrypoint on container
# startup, prior to the the database being started.
COPY initdb.sh /docker-entrypoint-initdb.d/init.sh
