os: linux
dist: trusty
sudo: required

language: bash

addons:
  hosts:
    - le1.wtf
    - le2.wtf
    - le3.wtf

env:
  global:
    - IMAGE=jrcs/letsencrypt-nginx-proxy-companion
    - NGINX_CONTAINER_NAME=nginx-proxy
    - DOCKER_GEN_CONTAINER_NAME=nginx-proxy-gen
    - TEST_DOMAINS=le1.wtf,le2.wtf,le3.wtf
    - DOCKER_COMPOSE_VERSION=1.24.0

matrix:
  include:
    - env: SETUP=2containers
    - env: SETUP=3containers
    - os: linux
      dist: xenial
      sudo: required
      env: SETUP=2containers
    - os: linux
      dist: xenial
      sudo: required
      env: SETUP=3containers
    - os: linux
      dist: bionic
      sudo: required
      env: SETUP=2containers
    - os: linux
      dist: bionic
      sudo: required
      env: SETUP=3containers
  allow_failures:
    - dist: bionic
  fast_finish: true

before_install:
  - test/travis/update-docker-compose.sh

install:
  - docker build -t "$IMAGE" .
  - docker inspect "$IMAGE"
  - docker run --rm "$IMAGE" simp_le --version
  - docker run --rm "$IMAGE" simp_le -v --test
  - docker images

before_script:
  - git clone https://github.com/docker-library/official-images.git official-images
  - test/setup/setup-boulder.sh
  - test/setup/setup-nginx-proxy.sh
  - docker pull nginx:alpine

script:
  - official-images/test/run.sh "$IMAGE"
  - test/run.sh "$IMAGE"

after_failure:
  - test/travis/containers-logs.sh
