ARG POSTGRES_VERSION
FROM postgres:${POSTGRES_VERSION}

RUN mkdir -p /docker-entrypoint-initdb.d

ARG JPY_PSQL_PASSWORD
ENV JPY_PSQL_PASSWORD ${JPY_PSQL_PASSWORD}
# initdb.sh will be run by the parent container's entrypoint on container
# startup, prior to the the database being started.
COPY ./server_apps/postgres-hub/initdb.sh /docker-entrypoint-initdb.d/init.sh
